name = "Jib"
uuid = "f310f2d2-a263-11e8-3998-47bd686f18f7"
authors = ["Luca Billi <noreply.section+dev@gmail.com>"]
version = "0.12.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
julia = "1.5"
